function (first letter to upper case)
js-tasks-ru/jsbasic-20201022_a-labocka pull request #2
Opened 2020-10-27 21:09 UTC by Alesia999

2020-10-28 01:28 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-28 02:35 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-28 09:16 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-29 12:51 UTC, koalex requested changes
Исправь замечание и сделай пуш

2020-10-29 12:51 UTC, koalex commented on 1-module/3-task/index.js
> +alert ( ucFirst( 'vasiliy' ) );
строку 11 надо удалить

2020-11-01 19:35 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Функция sumSalary(salaries)
+ должна возвращать 0 если нет свойств с зарплатами
+ должна складывать все зарплаты
+ должна игнорировать свойства других типов
```
```diff
Проверка на спам
+ должна возвращать true для '1XbeT now'
+ должна возвращать true для 'free xxxxx'
+ должна возвращать false для 'innocent rabbit'
```
```diff
Усечение строки
+ должна не трогать короткую строку 
+ должна усекать строку 
```
```diff
Сделать первый символ заглавным
+ должна делать первый символ заглавным
+ должна работать для пустой строки
+ должна работать для строки из одной буквы
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-11-01 19:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-01 21:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-03 00:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-03 12:53 UTC, koalex approved these changes

2020-11-03 12:54 UTC, merged